name: Dotnet Application CI

on:
  workflow_call:
  workflow_dispatch:
    

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo CI Message
        run: echo "Dotnet Application CI pipeline triggered!"
